
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app


COPY *.csproj ./
RUN dotnet restore


COPY . ./
RUN dotnet publish -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5212
ENTRYPOINT ["dotnet", "BlazorApp2.dll"]
